//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::cake::Entity as Cake;
pub use super::cake_filling::Entity as CakeFilling;
pub use super::filling::Entity as Filling;
pub use super::fruit::Entity as Fruit;
pub use super::post::Entity as Post;
pub use super::user::Entity as User;
